/** Prefix for all extension-injected DOM elements to avoid collisions */
export const ELEMENT_PREFIX = "__pd-";

/** Key CSS properties to extract from computed styles (Figma-relevant subset) */
export const TRACKED_PROPERTIES = [
  // Dimensions
  "width",
  "height",
  "min-width",
  "min-height",
  "max-width",
  "max-height",
  // Spacing
  "margin-top",
  "margin-right",
  "margin-bottom",
  "margin-left",
  "padding-top",
  "padding-right",
  "padding-bottom",
  "padding-left",
  // Layout
  "display",
  "position",
  "top",
  "right",
  "bottom",
  "left",
  "flex-direction",
  "flex-wrap",
  "justify-content",
  "align-items",
  "align-self",
  "gap",
  "grid-template-columns",
  "grid-template-rows",
  "grid-auto-flow",
  // Typography
  "font-family",
  "font-size",
  "font-weight",
  "line-height",
  "letter-spacing",
  "text-align",
  "text-decoration",
  "text-transform",
  "color",
  // Fill & Stroke
  "background-color",
  "background-image",
  "border-top-width",
  "border-right-width",
  "border-bottom-width",
  "border-left-width",
  "border-top-style",
  "border-right-style",
  "border-bottom-style",
  "border-left-style",
  "border-top-color",
  "border-right-color",
  "border-bottom-color",
  "border-left-color",
  "border-top-left-radius",
  "border-top-right-radius",
  "border-bottom-right-radius",
  "border-bottom-left-radius",
  // Effects
  "opacity",
  "box-shadow",
  "filter",
  "backdrop-filter",
  "overflow",
] as const;
